### ISSUE TITLE
sc.save()保存文件为空

### ISSUE THREAD

**Issue by 404563471** [SCMeTA/SCMeTA#2]
使用HeLa.RAW这个数据进行测试，按照文档的过程可以计算出结果，但是保存后文件为空

**Comment by EstrellaXD** [comment]
```python
sc.save(file_name, data_type)
```

**Comment by 404563471** [comment]
from SCMeTA import Process
sc = Process() 
sc.load('HeLa.RAW')
sc.pre_process() 
sc.process()
sc.save(file_name='HeLa',data_type='mat')

这是我测试的代码，在Process文件夹下得到一个Hela_mat.csv文件，是空的

**Comment by EstrellaXD** [comment]
Fix in #3

**Comment by 404563471** [comment]
我是用pip安装的这个python包，如何同步你的修改呢
